name: Fetch Cat Fact

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call Cat Fact API
        run: |
          echo "Calling catfact.ninja/fact..."
          curl -X GET "https://catfact.ninja/fact"
